apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: gateway-vllm
  labels:
    app: frontend
    app.kubernetes.io/part-of: ai-platform-vllm
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
