apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embedding-ollama-models
  namespace: embedding-vllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
